# Generated by Django 4.0.6 on 2022-08-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0002_remove_comments_comment_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
